### ISSUE TITLE
Создать структуру БД

### ISSUE THREAD

**Issue by alzv0411** [ncedu-tlt/ecomm#1]
- [x] Создать структуру БД по [схеме ](https://drive.google.com/open?id=0Bysv8raAy_4uR0lHZ3Y3dFlYNTQ) на внешнем сервере

- [x] Подготовить скрипт для создания таблиц и загрузить в ecomm/scripts/01_test_tables.sql

**Comment by ilyad777** [comment]
Добавил скрипт 6b8c8bb8b9e7dba2996c8508a2df9537102fa813

**Comment by alzv0411** [comment]
Илья, нужно перед созданием структур добавить в скрипт удаление (drop).
Т.е. чтобы они пересоздавались.

Скрипт перенес сюда: https://github.com/ncedu-tlt/ecomm/tree/master/scripts

**Comment by ilyad777** [comment]
Добавил DROP 748e016f215c3432f73bffb778a43ebdbdc95527
