### ISSUE TITLE
Компонент Registration

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#10]
Представляет собой форму для регистрации пользователя.

**Comment by Garthdex** [comment]
С вашего позволения чутка попозже займусь, пока учебной чепухой занят.

**Comment by ocassio** [comment]
1. Хотелось бы увидеть еще и клиентскую валидацию.
2. Подправь замечания, указанные в TODO.
3. ConfirmPassword - используем camelCase.
4. Используй параметры для имен URL.
5. Имена параметров вынеси в константы.
6. Дабы избежать большой вложенности условий, можно выполнять проверку и делать return, если нас что-то не устраивает в данных, предоставленных пользователем. В противном случае, можно продолжать выполнение функции.
7. Необходимо добавить хэширование пароля (синхронизируйтесь с Андреем, изменения нужно внести одновременно в сервлеты регистрации и логина).

**Comment by ocassio** [comment]
1. Вынеси все сообщения на JSP.
2. Для адресов страниц используем проперти.
3. Имена параметров/атрибутов - в константы.
4. Проверку формата email можно вынести в утильный класс, т.к. она много где используется.
5. .setRoleId(3) - Magic number.
6. getBoolUserByEmail - Зачем нам метод, который практически полностью дублирует получение пользователя по email? Используй getUserByEmail и делай проверку на null.
7. Для отображения серверных ошибок можно использовать тот же блок, что и для клиентских.

**Comment by ocassio** [comment]
req.setAttribute(REGISTRATION, "Registration success! Please sign in"); - Тоже вынеси в JSP.
В остальном все нормально. Тикет закрываю.
