### ISSUE TITLE
Компонент Password Recovery

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#11]
Компонент позволяет указать email для отправки инструкций по восстановлению пароля.

**Comment by lordever** [comment]
На данный момент сдаю сессию. Буду периодически выполнять работу, но медленно. Сессия продлится до 21 декабря

**Comment by ocassio** [comment]
1. type: 'length[' + 4 + ']' - Что тебе помешало написать 'length[4]'?
2. this.content.find('.ui.form') - Исползуем спец. классы.
3. Какой-то экзотический способ получения параметров:
```java
        String pattern = req.getQueryString();
        String[] parametersFromUrl = pattern.split("&");
        String[] parameters = parametersFromUrl[0].split("=");
        String email = parameters[1];
```
4. Можно просто вернуть резульат сравнения. Следи за подсказками идеи:
```java
        if(recoveryHash.equals(userByEmail.getRecoveryHash())){
            return true;
        }
        else{
            return false;
        }
```
5. Волшебные числа:
```java
        while (uniqueHash.size() < 10) {
            uniqueHash.add(random.nextInt(9));
        }
```
6. В таких случаях следует использовать StringBuilder. Увеличивает производительность.
```java
        String recoveryHash = "";
        for (Integer hash : uniqueHash) {
            recoveryHash += hash.toString();
        }
```
7. Inline стиль. Так делать не стоит:
```html
 <form class="ui form" style="margin: 5em 0" method="post"
                          action="#">
```

**Comment by lordever** [comment]
2. Специальные классы это к примеру так?
<form class="ui form jsPasswordRecoveryForm" method="post"
                          action="#">

3. Пока что не нашёл более лучшего решения этой проблемы

**Comment by lordever** [comment]
<form class="ui form jsPasswordRecoveryForm" method="post"
                          action="#">

**Comment by lordever** [comment]
2. Специальные классы это примерно вот так?
`<form class="ui form jsPasswordRecoveryForm" method="post"
                          action="#">`
3. Я пока не нашёл решения этой проблемы без применения стольких функций.

**Comment by ocassio** [comment]
2. Да.
3. Еще в первых заданиях получали параметры. Например, вот так: https://github.com/ncedu-tlt/ecomm/blob/master/src/main/java/ru/ncedu/ecomm/servlets/LoginServlet.java

**Comment by ocassio** [comment]
Пробегись по TODO.

**Comment by lordever** [comment]
Мне не совсем понятно как вынести это в отдельный файл. У меня есть 2 аргумента, которые мешают вынести текст в Property
`private String getTextHtml(String toEmail, String recoveryHash) {
        return "<p>Please change your password in here:</p>" +
                "<a href='https://ncedu-ecomm-dev.herokuapp.com/passwordChange?email="
                + toEmail + "&recoveryHash=" + recoveryHash + "'>Change Password</a>";
    }`

**Comment by ocassio** [comment]
Я подразумевал использование каких-либо темплейтов. Эта пометка больше для пятничной встречи, чем для выполнения. А вообще тут есть еще один недостаток - ты захардкодил адрес сервера.

**Comment by ocassio** [comment]
1. NPE при указании незарегистрированного email.
2. getRecoveryHashByEmail - Судя по названию, должен получать на вход email. Де-факто такого нет. Также вся логика заключается лишь в вызове другого метода.
3. В таких случаях используют StringBuilder (об этом даже сама идея кричит):
   ```java
   String recoveryHash = "";
   for (Integer hash : uniqueHash) {
       recoveryHash += hash;
   }
   return recoveryHash;
   ```
4. Хватит объявлять константы внутри методов. Так они создаются при каждом вызове.
5. Так, к слову, у нас отсутствует проверка на коллизии при генерации хэша.
6. Страницы из пропертей, имена в константы, сообщения на JSP.

**Comment by ocassio** [comment]
1. `String contextPath = req.getServerName();` - Если мы изменим контекст на отличный корневого, то отошлем юзеру неверную урлу.
2. Пункт 4 не выполнен.
3. Используй цикл с постусловием. Это позволит избежать дублирования кода:
   ```java
   String recoveryHash = generateRecoveryHash();
   UserDAOObject userByHash = getDAOFactory().getUserDAO()
           .getUserByRecoveryHash(recoveryHash);
   while(userByHash != null){
       recoveryHash = generateRecoveryHash();
       userByHash = getDAOFactory().getUserDAO()
               .getUserByRecoveryHash(recoveryHash);
   }
   ```
4. Пункт 6 касается и сервисов.
5. `!Objects.equals(recoveryHash, "")` - Используй StringUtils.
6. Тут не нужен else:
   ```java
   if(!Objects.equals(recoveryHash, "")) {
       UserDAOObject userByEmail = getDAOFactory().getUserDAO().getUserByEmail(userToRecovery.getEmail());
       return recoveryHash.equals(userByEmail.getRecoveryHash());
   }
   else
       return false;
   ```
7. `recoveryHash.append("");` - В чем смысл?
8. Нейминг методов. Запомни, имя метода - всегда глагол, обозначающий одно действие, которое будет выполнено. Примеры ошибок:
   1. actionOnErrorCheckEmail - Существительное.
   2. getAnswer - Получает юзера, генерит хэш и отправляет письмо. Метод при этом называется "получить ответ".
   3. sendingLetterToEmail - Обозначает процесс, а не действие. Внутри вообще происходит запись хэша в модель пользователя (причем без записи в базу, это действие почему-то выполняется в методе sendMailToUser).
   4. getRecoveryHashAfterChecking - AfterChecking только смутит другого разработчика. Мы получаем хэш, детали реализации не важны.
   5. И т.д., и т.п.
9. Зачем при вызове методов сервиса из самого сервиса, ты получаешь его через getInstance()? Ты и так внутри объекта, для чего нужно совершать дополнительные телодвижения?

**Comment by ocassio** [comment]
getContextPath - Посмотри как он получается в RedirectUtil, не нужно пилить свою имплементацию. В остальном все более-менее нормально, тикет закрываю.
