### ISSUE TITLE
Компонент Categories

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#13]
Меню категорий.
Отображаем только три первых уровня иерархии.

**Comment by ilyad777** [comment]
Пока так 4a5215ecd4fb06d58091b80fa5ca41a710cd7885

**Comment by ilyad777** [comment]
Ссылки пока не добавлял

**Comment by ocassio** [comment]
Мельком глянул, попозже еще посмотрю.
Пока следующие замечания:
1. Зачем нам два одинаковых класса Categories и Middles?
2. Не нужно разводить внутренние классы, сделай полноценную вью модель, имеющую идентификатор, имя и список дочерних категорий.

**Comment by ilyad777** [comment]
Спасибо, сделаю)

**Comment by ilyad777** [comment]
Готово 88c6ad27952e6ed32b7f246f375d19d788db8034

**Comment by ilyad777** [comment]
Поспешил, не готово

**Comment by ilyad777** [comment]
Готово 3a50b4050cdc2d0d893b705c8a595aa1451eec2f

**Comment by ocassio** [comment]
1. Слишком сложная логика в JSP. Сделай нормальную иерархию внутри CategoriesViewModel и делай простой вывод в соответствии с ней. Если что, Ваня может подсказать, я ему уже делал подобное замечание.
2. urlPatterns = {"/CategoriesServlet"} - сделай просто /categories
3. \category? - обратные слеши использует только Windows. Во всех остальных случаях, пути пишутся с прямым слешем.
4. Хотелось бы увидеть кликабельные категории первого уровня.

**Comment by ilyad777** [comment]
Посмотри пожалуйста, по идее все учел 32a90dc72a5d9d59cd52dcc563a1be6700ea00c1
