### ISSUE TITLE
Доработать Product List и сервлет для категорий

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#16]
Сейчас слишком много логики выполняется в JSP.
Нужно создать view модель такого вида, которая позволит выводить категории и их содержимое просто пробегаясь по списку. Вся логика по формированию данных в нужном формате должна располагаться в сервлете.

**Comment by jegius** [comment]
ae6320156e1f5f77dfee3b71b18b20434275aece
Саш Готово!

**Comment by ocassio** [comment]
Вань, нужно доработать:
1. У тебя по прежнему плоский список с новой view моделью. Из-за этого появляется лишняя логика в JSP. Модель можно сделать иерархичной, т.е. категория с id, именем и списком товаров.
2. В модели зачем-то присутствует discountId. Зачем нам нужен идентификатор? Кстати, он даже не используется. :) А вот саму скидку хотелось бы увидеть как в модели, так и в JSP.
3. Давай оставим в пакете ru.ncedu.ecomm.data.models только модели, относящиеся к БД. View модели можно расположить, к примеру, в пакетах ru.ncedu.ecomm.data.viewmodels или ru.ncedu.ecomm.servlets.models.

Также общие замечания:
1. Всегда оставляй пустой конструктор для POJO. Далеко не всегда разработчик захочет заполнять все поля, а многие библиотеки вообще отказываются работать с моделями без конструкторов по умолчанию.
2. Не злоупотребляй билдерами. Они не всегда оправданы.
3. Следи за наименованиями. К примеру, функции всегда означают какое-либо действие. У тебя же замечаю функции типа itemView и categoriesFilter. Это существительные и не очень то понятно, что они должны делать. Хотя в некоторых случаях это оправдано, к примеру, частенько бывают билдеры вида:
```java
new DialogBuilder()
    .title("Some Title")
    .text("Message")
    .build();
```

**Comment by jegius** [comment]
Принял

**Comment by jegius** [comment]
52eceb21db03f4b7648296a1ce54d29459a3af5b
Проверь пожалуйста новую версию

**Comment by ocassio** [comment]
По общей логике:
1. Почему, в случае отсутствия категории с указанным идентификатором, мы выводим первую категорию? К примеру, у нас есть категории Computers, Food и Sporting Goods со своими подкатегориями. Почему мы отобразим именно Computers? И что будет в том случае, если у нас не будет категории с идентификатором 1?
2. final int CHARACTERISTIC_ID_FOR_ONE_CATEGORY = 28;
    final int CHARACTERISTIC_ID_FOR_FIVE_CATEGORY = 29;
    Вот этой фишки я вообще не понял. У нас должно быть наследование характеристик.
3. Сортировку лучше производить на уровне базы данных.
4. Зачем мы отображаем сверху текущую категорию и её товары, и только затем подкатегории?
5. Зачем мы отображаем дочерние категории дочерней категории сразу же за ней?

Прочее:
1. DEFAULT_VALUE - константа исключительно по наименованию. Константы объявляем как поле класса с модификаторами static final. В таком случае, значение будет инициализировано только один раз, а попытки изменения будут пресечены еще на уровне компиляции.
2. Про метод itemView я уже говорил. Это существительное, оно не означает никакого действия. Соответственно, непонятно, что именно выполняет этот метод.
3. Часто вижу несоответствие чисел в наименованиях.
4. addAllChildCategory - метод **получает** **список** дочерних категорий, а называется так, будто **добавляет** **все** дочерн**юю** категор**ию**. Лучше назвать getChildCategories. Внутри метода также разберись с наименованиями.
5. Для чего нам в методе addAllChildCategory Set и List одновременно?
6. String imageUrl = "\\images\\defaultimage\\image.png"; - Во-первых, это явно нужно вынести в константу. Во-вторых, используй специальные разделители. Уже обсуждалось в процессе разработки консольного приложения.
7. categoryByRequest.getChildCategory().size() != 0 - Есть метод isEmpty().
8. Пакет viewmodel. Во-первых, там много моделей, а не одна => viewmodels. Во-вторых, можно упростить до models, так как мы уже находимся в пакете servlets.
9. Пакет viewmodelbuilders можно упростить до builders. Для чего они нужны, понятно из контекста.
10. ProductItemsView - судя по названию, это вьюха для отображения нескольких Product Item'ов. Правильнее будет ProductViewModel.
11. CategoryViewModel:
     а. categoryId - оно и так в категории => id.
     б. parentId - оно нам вообще нужно?
     в. categoryName - name.
     г. childCategory - опять же, список => children или categories.
     д. productInCategory - список + они и так внутри категории => products.
12. ProductItemsView:
     а. categoryId - для чего?
13. Давно у нас урлы обратный слэш используют?)

**Comment by jegius** [comment]
Снова принял

**Comment by jegius** [comment]
Саш проверь пожалуйста еще раз) 
И у меня вопросы по пунктам 4, 5

**Comment by jegius** [comment]
Я закончил) 4e73fe896b8456e6958ca9b315ff028cbd40c24b
