### ISSUE TITLE
Компонент Profile

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#17]

**Comment by lordever** [comment]
Саш, объясни пожалуйста что в этом компоненте мы конкретно хотим добиться?

**Comment by ocassio** [comment]
Отображение информации о пользователе, а также возможность редактирования профиля.

**Comment by lordever** [comment]
На странице profile только отображение полей для ввода информации о пользователе. Как я понял для пользователя есть возможность ввести подробную информацию о себе, позже она будет отображаться на этой странице, где каждую из полей можно будет отредактировать. Данную информацию также нужно будет сохранить в бд. Мне нужно также создать таблицу в БД для хранения этих данных. Я всё правильно рассписал?

**Comment by ocassio** [comment]
Обязательные поля пользователь указывает еще при регистрации. На этой странице отображается вся информация о пользователе, которую он может изменять.

А зачем нам отдельная таблица, если у нас уже есть Users, в которой имеются все необходимые нам поля?

**Comment by lordever** [comment]
о дополнительных полях в базе я ошибся. Думал, что в профиле должна быть другая информация.

**Comment by lordever** [comment]
В dashboard на странице профиля нужно ещё сделать orders history ещё? Если нужно то как его сделать?

**Comment by ocassio** [comment]
Нет, Orders History - отдельная страница.

**Comment by ocassio** [comment]
Глянул мельком, сразу пара замечаний:
1. Пользователя нужно определять не по параметру в URL, а по данным, хранящимся в сессии. В противном случае, доступ к личным данным открыт для всех.
2. Распиши логику работу метода changeProfile, там явно что-то не то происходит.

**Comment by lordever** [comment]
Я наверное не правильно понял... Я так понял, что данные в сессию попадают при авторизации пользователя. Авторизации пока не было, но тестировать мне как то нужно было, поэтому я просто через URL это сделал. 
Про логику change profile меня тоже смущает результат. Но я не могу понять что именно мне не нравится

**Comment by lordever** [comment]
Я изменил логику изменения профиля. Посмотри пожалуйста

**Comment by ocassio** [comment]
1. Мы должны отображать текущие значения полей при заходе на страницу.
2. Не давать юзеру засабмитить форму, если есть пустые поля.
3. userById.getFirstName() != firstName - Строки - это объекты. Их нельзя сравнивать через ==, только через equals.
4. Если необходимые данные уже есть, то не нужно выполнять лишние запросы к БД. Вот тут у нас выполняется пять запросов по получению пользователя:
```java
        User user = getDAOFactory().getUserDAO().getUserById(userId);
        String firstName = getFirstName(req.getParameter("firstName"), userId);
        String lastName = getLastName(req.getParameter("lastName"), userId);
        String email = getEmail(req.getParameter("email"), userId);
        String password = getPassword(req.getParameter("password"), userId);
```
5. В JS не стоит завязываться на классы, необходимые для оформления. Вместо этого стоит использовать специальные классы: jsClassName.

**Comment by lordever** [comment]
2. Если пользователь хочет изменить только своё имя, ему придётся вводить все параметры. Как я понял, в значении самих полей отобразить текущие значения полей?

**Comment by ocassio** [comment]
Мы всегда отображаем текущие значения, эта же страница используется и для просмотра информации. Если пользователь хочет что-то изменить, то он изменяет эти поля и сабмитит форму.

**Comment by ocassio** [comment]
1. А у нас пароль можно поменять не вводя подтверждение и старый пароль?
2. Необходимо добавить хэширование пароля (одновременно с Андреем и Антоном).
3. Сервлет ProfileChange не нужен. Можно просто использовать запрос с GET для отображения и c POST - для обновления.
4. Внеси правки с нашего прошлого разговора (как минимум, приведи в порядок сервисы).
5. Ну и правки по TODO.

**Comment by ocassio** [comment]
1. Не проверяется старый пароль.
2. Новый пароль должен быть опциональным.
3. Текстовые сообщения в JSP.
4. Имена атрибутов и параметров в константы.

**Comment by ocassio** [comment]
Замечания проговорили в скайпе.
