### ISSUE TITLE
Главная страница

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#18]
На главной странице нужно отображать секцию Best Offers, в которой будут расположены товары с наибольшими скидками.
Под капотом все тот же Product List.
Также необходимо ввести максимум отображаемых товаров на категорию. К примеру, на странице category можно поставить ограничение в 6 товаров на категорию, а на главной странице - 12.

**Comment by jegius** [comment]
Саш как мне зафорвордить продукт лист на главную страницу, и как сделать бест оферс? как отдельный компонент со своим сервлетом или на базе сервлета категории?

**Comment by ocassio** [comment]
Компонент тот же, сервлет и страница другие.

**Comment by jegius** [comment]
ffef8eadbf494f3745b9ef3df76187058b4b5308 
готово! Саш проверь пожалуйста

**Comment by ocassio** [comment]
Просуммирую замечания по /home и /category:
1. Если на /category не указана категория, то нужно выводить корневые категории (Computers и Video Games, на данный момент).
2. Зашивать такую логику в сервисе - неправильно. В коде сервлета должно быть четкое понимание того, какие данные мы получим.
```java
if (request.getServletPath().equalsIgnoreCase(HOME_PAGE_URL)) {
```
3. Давай немного изменим логику /home страницы. Будем выводить Best Offers, а затем корневые категории.

Ну и так, напоследок. Вот это уже борщ:
```java
    private boolean checkInNull(Object object) {
        return object == null;
    }
```

**Comment by jegius** [comment]
принял поправлю

**Comment by jegius** [comment]
3aa4590e31a53e5d9319c24be6a7cc160fab0aa1 Готово!

**Comment by jegius** [comment]
3965c922afa7aab8908024d79f8737adbd06cf41 правка по третьему пункту

**Comment by ocassio** [comment]
Еще одно небольшое замечание по сервису.
Получение идентификатора категории из реквеста и запрос других данных в случае его отсутствия лучше вынести в сервлет.
Это вызвано тем, что имена параметров в сервлетах могут отличаться, а также может быть различная логика в случае отсутствия значения параметра.
Также имена параметров желательно выносить в константы.

**Comment by jegius** [comment]
Перенес логику обработки запроса на сервлет
3692b334caca9c30e5ff59aa101fd8253bf018b4

**Comment by ocassio** [comment]
```java
static final String PARAMETER_NAME_FOR_CATEGORY_ID = "category_id";
```
1. Забыл сделать приватным.
2. CATEGORY_ID_PARAM вполне достаточно. Длинные названия только Apple приветствует.

Не это уже мелочи. :)
Тикет закрываю.
