### ISSUE TITLE
Компонент Product Details

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#19]
Компонент отображает подробную информацию о товаре.

**Comment by jegius** [comment]
34f733df7dd8ab6dc2a50417cb26b5028ea67ef0 
Cаш готово! Проверь пожалуйста

**Comment by ocassio** [comment]
1. Зачем тебе productId в CharacteristicGroupModel?
2. characteristicGroupName - такие вещи можно упрощать до name. По имени объекта и так понятно, чье это имя.
3. Пробегись по наименованиям и советам от идеи. Достаточно много замечаний.

**Comment by jegius** [comment]
3692b334caca9c30e5ff59aa101fd8253bf018b4
поправил
