### ISSUE TITLE
Создать тестовые данные

### ISSUE THREAD

**Issue by alzv0411** [ncedu-tlt/ecomm#2]
- [x] Создать тестовые данные на внешнем сервере

- [x] Подготовить скрипт для данных и выложить в ecomm/scripts/02_test_data.sql

**Comment by AndrewKozyrin** [comment]
Начал создание текстовых данных

**Comment by alzv0411** [comment]
Андрей, а ты выложишь скрипт для создания данных в https://github.com/ncedu-tlt/ecomm/tree/master/scripts?

**Comment by AndrewKozyrin** [comment]
Выложил в гугле еще в понедельник
https://drive.google.com/drive/folders/0B3sokuzkt4LSN1BRejNOVzNhNEE. Сейчас
выложил и на гит хабе. В гугле, в папке утилс, также выложил скрипт на
полную очистку всех данных во всех таблицах со сбросом сиквенсов, на всякий
случай.
Еще момент в скрипте на создание таблиц, возможно нужно поправить
1. character varying[] на character varying,
2. В таблице product - name изменил character varying(100)  на character
varying(250)
3. В characteristic_values - value character varying(255)
4. Добавил в ревью чек для рейтинга:
ALTER TABLE reviews
CONSTRAINT raiting_check_for_ten CHECK (raiting >= 0 AND raiting <= 10);

2016-12-07 11:03 GMT+04:00 Alexander Zvyagintsev <notifications@github.com>:
