### ISSUE TITLE
Компонент Shopping Cart Icon

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#20]
Иконка в верхней части экрана.

Отображает количество товаров в корзине.
При клике осуществляется переход на страницу корзины.

Также будет отвечать за добавление товаров, а именно:
1. Будет слушать событие addToCart с параметром id.
2. Полученные параметры будут посылаться в запросе на специальный сервлет.
3. В случае успеха, будет происходить обновление текущей страницы.

**Comment by lordever** [comment]
Возникли вопросы: 
Где нужно хранить количество добавленных товаров в корзину? 
Обновление счётчика shoppingCartIcon должно происходить из сервлета? 
Я так понимаю после добавления товара мы где то храним количество товаров и их productId, и обновляем счётчик следуя количеству добавленных товаров, так?

**Comment by ocassio** [comment]
> Где нужно хранить количество добавленных товаров в корзину?

В таблице order_items.

> Обновление счётчика shoppingCartIcon должно происходить из сервлета?

Страница же будет обновляться, при отрисовке там будет новое значение.

> Я так понимаю после добавления товара мы где то храним количество товаров и их productId, и обновляем счётчик следуя количеству добавленных товаров, так?

Да. Табличка sales_orders и связанные с ней.

**Comment by lordever** [comment]
Доделал. Java script просто берёт get параметр и выводит значение в иконке. Я думаю добавить ещё ajax и сделать так как ты сказал с добавлением события addToCart

**Comment by ocassio** [comment]
1. Настрой ESLint, увидишь приличное количество замечаний к JS коду.
2. $(".shoppingCartIcon") - глобальный селектор. А если мы сразу несколько таких компонентов на странице разместим? Используй this.content.find('.shoppingCartIcon').
3. Отдельный запрос из JS ради количества товаров в корзине? Печатай из JSP. Получение данных можно сделать по тому же принципу, что и Breadcrumbs у Ильи.
4. window.location.replace("/views/pages/cart.jsp"); - Replace замещает текущую страницу, т.е. из истории она пропадет, и юзер не сможет перейти назад. Можно сделать через window.location.href, либо вообще сделать иконку ссылкой, что даже лучше.
5. var counter = new Number($(".counter").text()); - Столько телодвижений, а даже не используется.

**Comment by ocassio** [comment]
1. ESLint по прежнему не настроен.
2. Зачем нам alert на каждой странице?
3. Константы должны быть полями статическими полями класса, в противном случае мы заново инициализируем ее при каждом вызове метода.
4. А если у юзера реально id 0? Используй null.
   ```java
   if (userId == 0) {
        req.setAttribute("quantityProducts", EMPTY_QUANTITY);
   }
   ```
5. В сессии и так лежит long. Зачем приводить его к String, а затем парсить?
   ```java
   Long.parseLong(authorization.getAttribute("userId").toString())
   ```
6. Следи за замечаниями от идеи. Например, в данном случае, нет нужды создавать лишнюю переменную:
   ```java
   int quantityProducts = salesOrderByUserId.size();
   return quantityProducts;
   ```
7. Почему у нас отображается количество всех заказов, когда-либо совершенных пользователем, вместо количества продуктов в корзине?

**Comment by ocassio** [comment]
В общем и целом все хорошо.
Мелкие хотелки:
1. shoppingCartIcon.html().trim() === '' - Можно спокойно сократить до shoppingCartIcon.html().trim(). С точки зрения JS, пустая строка == false.
2. Хотелось бы увидеть какое-то зрительное оповещение о том, что происходит процесс добавления в корзину, так как эта операция занимает довольно длительное время, и пользователь может успеть несколько раз нажать на кнопку, думаю, что что-то не работает.
Как вариант, какой-нибудь оверлей с лоадером.

**Comment by ocassio** [comment]
Также не забываем про тикет https://github.com/ncedu-tlt/ecomm/issues/32.

**Comment by ocassio** [comment]
1. getProductsBySalesOrderId - не отражает суть происходящего.
2. final int EMPTY_QUANTITY = 0; - константа.
3. Имена атрибутов и параметров в константы.
4. Это не внутренняя ошибка, а вполне штатная ситуация:
   ```java
   if (!userInSystem) {
       resp.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
   }
   ```
5. Разберитесь с производительностью метода добавления. Там явно много лишних телодвижений.
6. $('#jsDimmerAdd') - Глобальный селектор и идентификатор. Комбо :)
7. Сделай все анонимные функции методами контроллера.
8. shoppingCartIcon.html().trim() - Можно сократить до !shoppingCartIcon.trim().
9. window.location.replace('/login'); - Это замена урлы текущей страницы, а не переход на новую (при нажатии на кнопку Назад в браузере одна страница будет пропущена). Используй window.location.href = '/login';

**Comment by ocassio** [comment]
1. Пункты 2 и 3 не выполнены.
2. ` <button onclick="window.location.href = '${pageContext.request.contextPath}/cart'" class="circular ui icon button">` - Используй ссылку.
3. this.params.baseIconUrl + '/addToShoppingCart' - Нужно присылать уже готовую ссылку.
4. Пункт 7 не выполнен.
5. А зачем нам анимация при изначальном отображении?
6. Отображение dimmer'а размазано аж на три функции хотя операция простая.

**Comment by ocassio** [comment]
1. При добавлении товара оверлей не исчезает.
2. `long emptyQuantity = 0;` - Я уже сбился со счета, сколько раз я писал про то, где должны объявляться константы.
3. Мы же договорились, что решение об изначальном отображении иконки должна принимать JSP, а не JS.
4. Пункт 4 по прежнему не выполнен.
5. Зачем мы инициализируем оверлей перед каждой отправкой запроса?

**Comment by ocassio** [comment]
1. Dimmer должен быть полем класса. Сейчас у тебя будет одна переменная на все инстансы shoppingCartIcon.
2. `complete: setTimeout(this.dimmerToggle, 1000)` - А зачем нам тут задержка?
3. Удали класс jsShoppingCartComponent из shoppingCartIcon.jsp. Из-за этого может инстанцироваться еще один контроллер корзины.

**Comment by ocassio** [comment]
Первый пункт пропустил.
