### ISSUE TITLE
Компонент Search

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#21]
Строка поиска в верхней части экрана.

После ввода запроса и нажатия на клавишу Enter происходит запрос на новый сервлет, который ищет в БД продукты, содержащие строку запроса в своем имени.
Для отображения используется компонент Product List без группировки по категориям.

**Comment by ilyad777** [comment]
Готово 6d94b306b98cc9f4d744624a0b9960c384741606

**Comment by ilyad777** [comment]
Учел замечания, по поводу пустых запросов 3f03cc72ad8a1a4779a203dd3a1104841d67b8bc

**Comment by ocassio** [comment]
Давай лучше не будем ничего делать, если пользователь не ввел запрос и нажал клавишу Enter.

**Comment by ilyad777** [comment]
Готово 32a90dc72a5d9d59cd52dcc563a1be6700ea00c1

**Comment by ocassio** [comment]
1. Сейчас при попытке выполнить запрос мы выполняем приличное количество операций, при этом оказываемся на главной странице, а адрес у нас /search. Я хочу, чтобы при нажатии на клавишу Enter не происходило ровным счетом ничего.
2. Сделай запрос на /search страницу через GET. Тогда пользователь сможет передавать ссылку на результаты поиска третьим лицам.

**Comment by ilyad777** [comment]
Сделал, скрипт загрузил в папку searchComponent из-за того что папка search игнорится гитом
поправить это не получилось(  05ef1d49b903563ea01dc103651d70a9acdd596f d0e5ec45968b958abb59deaafc88b7e9d71a41e5

**Comment by ilyad777** [comment]
Вроде разобрался, в идее не стоял плагин гитигнор и гит игнорировал search из-за того что в начале написано слово Search, поставил плагин все заработало как положено.

**Comment by ocassio** [comment]
Ну плагин тут не причем. А вот в .gitignore действительно какой-то мусор попал.

Замечания:
1. Настрой ESLint. Увидишь стилистические ошибки в JS.
2. Не нужно определять никакого HIDDEN_ID. Просто не отображаем скидку, если в id null.
3. Компоненты должны быть реюзабельными, в том числе и по несколько одинаковых компонентов на одну страницу. Соответственно, всю клиентскую логику необходимо изолировать:
   - Не используем глобальные селекторы в духе $('.someClassName'). Вместо этого ищем элементы внутри компонента: this.content.find('.someClassName').
   - Не используем идентификаторы. Исключительно классы. Причем, если на них идет завязка в JS, то используется формат jsSomeClass.
4. Данный код:
   ```javascript
   if ($('#text').val().replace(/^\s+|\s+$/g, '')) {
   ```
   Можно упростить до:
   ```javascript
   if ($('#text').val().trim()) {
   ```
5. Старайся не использовать множество одинаковых селекторов там, где этого явно можно избежать. Поиск элемента - сравнительно дорогая операция.
6. Старайся избегать использования вложенных анонимных функций. Они усложняют восприятие кода, а в некоторых случаях и влияют на производительность. Лучше объявить отдельную функцию-обработчик и просто сослаться на нее:
   ```javascript
   $('#searchForm').submit(this.onSubmit);
   ```
7. Зачем нам нужно динамически определять action на форме, если он всегда один? Перенеси в JSP.
8. Если ты вешаешь обработчик на submit, то тебе достаточно вернуть false, чтобы прервать процесс сабмита. Если ты не вернешь ничего, то процесс просто пойдет дальше. Искусственно вызывать его еще один раз не требуется.

**Comment by ilyad777** [comment]
По второму пункту, id в CategoryViewModel типа long, null быть не может, соответственно я подстраиваюсь под готовый код. 
По остальным поправил 64a72329bb7c844776de378c0df49c72162ee6aa

**Comment by ocassio** [comment]
Может, если заменить long на Long.

**Comment by ilyad777** [comment]
Можно и заменить

**Comment by ilyad777** [comment]
4c02a9b3b209facf951b4aa21cedd488cd971497 заменил, спасибо за комментарии)
