### ISSUE TITLE
Компонент Profile Icon

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#22]
Логика работы:
- Если пользователь не вошел в систему, то отображаем иконку входа в систему и выполняем перенаправление на страницу логина при клике.
- Если пользователь вошел в систему, то отображаем иконку профиля и выполняем перенаправление на страницу профиля при клике.

**Comment by ocassio** [comment]
1. На самом деле, нам не нужен дополнительный сервлет для данного кейса. Достаточно добавить проверку на наличие пользователя в сессии в Profile сервлете и делать редирект в случае неудачи. Кстати, эту логику лучше вынести в сервис, так как она будет использована и в других сервлетах.
2. После редиректов сохраняется урла сервлета.
3. Почему для перехода по урле используется форма? Это же обычная ссылка.

**Comment by ocassio** [comment]
Саш, а зачем ты сделал отдельный сервлет с проверкой на авторизацию пользователя + аналогичную проверку в сервлете профиля + вызов метода, который выполняет аналогичную проверку?

**Comment by lordever** [comment]
по не знанию сделал ошибку, но я её осознал и буду стараться не писать полно одинакового кода!) Андрей кажется сделал уже проверку на авторизацию пользователя. Я думаю можно все методы работающие с пользовательскими данными написать в сервисе пользователя.
