### ISSUE TITLE
Компонент Reviews

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#24]
Список отзывов о товаре.

**Comment by jegius** [comment]
Готово! 9967b2d596f36a6f1e747dad9bdd61a5c87ab978
С одной оговоркой. Саш где должны храниться аватары юзеров?

**Comment by jegius** [comment]
699e4d977113e6132ed7a14a2e43b9e84b8e4c4f
добавил аватар в таблицу users и в модель user, в таблице установлено значение по умолчанию со ссылкой на дефолтный аватар

**Comment by ocassio** [comment]
Ок, пусть будет так.

**Comment by jegius** [comment]
Тогда все готово

**Comment by ocassio** [comment]
1. Не надо выставлять email пользователя напоказ. Напиши что-нибудь в духе Anonymous.
2. Нейминг снова местами страдает.
3. Не пугай такими штуками :)
![2017-01-24 21 01 57](https://cloud.githubusercontent.com/assets/6851647/22257735/5f523a30-e278-11e6-9ea2-3d5eaaf4b83c.png)

**Comment by jegius** [comment]
2a0aa41746fe24a1b3714c10c25c500e9dd5bc07
5e43254e8783c0dc248c0febd92b451bc3e8153f
Поправил
