### ISSUE TITLE
Компонент Filtering

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#25]
Панель фильтрации.
Отображается фильтрация по цене (диапазон) и по всем характеристикам (checkbox'ы) текущей и родительских категорий, отмеченным как filterable (новое поле в таблице).
Для начала задача - просто построить список фильтров.

**Comment by ilyad777** [comment]
Сделал построение списка 4621c64794ef14dc32566942366c576e4c0916ca

**Comment by ocassio** [comment]
А ценовой диапазон?

**Comment by ilyad777** [comment]
В процессе....

**Comment by ilyad777** [comment]
Добавил фильтрацию по диапазону цен a1125f94f25cc38c085ce1bacfc50d20fee162a9

**Comment by ilyad777** [comment]
Саш, как лучше организовать фильтрацию?
Огромным запросом в базу, в котором учитывать и диапазон цен и параметры фильтрации или же получать продукты по диапазону цен и их уже фильтровать в сервлете?

**Comment by ocassio** [comment]
Запрос быстрее отрабатывает, так что, думаю, лучше его.

**Comment by ilyad777** [comment]
Готово 441dad819aa9020a0e00d7d7deb5ae0c36353503

**Comment by ilyad777** [comment]
Вот теперь думаю точно готово) 6fc2ec3e738d2ecb148f7148fc09fd02a529b6c5

**Comment by ocassio** [comment]
Сейчас зашел в категорию Laptops и открыл фильтр. Увидел в качестве вариантов для выбора бренды, которые не представлены в данной категории, но есть к примеру в Tablets.

**Comment by ilyad777** [comment]
Поправил запросы, теперь работает как нодо
