### ISSUE TITLE
Компонент Orders History

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#26]
Отображаем все заказы в статусе Completed.

**Comment by ocassio** [comment]
Падает при открытии страницы под пользователем:
Email: test@test.com
Пароль: test

**Comment by ocassio** [comment]
По поводу ошибки, во время построения списка выполняется огромное количество запросов к БД (нужно разбираться вместе с Андреем, методы написаны не самым оптимальным способом). Если локальный сервер довольно непривередлив и спокойно дожидается ответа, то CI себе такого позволить не может и падает с ошибкой.

Далее по замечаниям:
1. Администраторы на этой странице ничем не должны отличаться от обычных пользователей.
2. Не думаю, что стоит отображать заказы, в которых ничего нет.

**Comment by ocassio** [comment]
А почему у нас DAO возвращает view model?

**Comment by jegius** [comment]
eddd0bb25562d8b697de75bc564c35135c09000f объекты переименованы
