### ISSUE TITLE
Reviews - Возможность добавлять новый комментарий

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#27]
Если пользователь залогинен и еще не оставлял отзыв для данного товара, то отображаем соответствующую форму.

**Comment by jegius** [comment]
Саш нужна помощь по двум пунктам:
1) немного не в этой задаче: https://ncedu-ecomm-dev.herokuapp.com/category 
не понимаю в чем ошибка.
2) я почему то не могу на сервлете для review прочитать пост запрос, он почему то пустой приходит.

**Comment by jegius** [comment]
2a51340bc8a59a6541be660e925e432983b1982f

Саш добавление отзыва реализовал, но решил что было бы неплохо сразу реализовать и редактирование и удаление. Как лучше это сделать?

**Comment by ocassio** [comment]
Пусть собственный отзыв отображается первым.
С удалением непоняток быть не должно.
А при редактировании нужно заменять снова отобразить форму добавления, но уже с заполненными данными.

**Comment by jegius** [comment]
Саш Все готово. 6753d18359fabebc56915ea6426f21e3f812816d

**Comment by ocassio** [comment]
1. if (req.getParameter("reviewActions").equals("add")) { - Такие вещи лучше делать через switch с вынесением каждого действия в отдельную функцию. Здорово повышает читабельность.
2. Имена параметров и возможных значений лучше вынести в константы.
3. Хотелось бы увидеть возможность отмены редактирования.
4. Зачем нам отдельный компонент для редактирования? Вьюха - ок, а вот дополнительный контроллер тут явно лишний.
5. Одна переменная - один var.
6. this.content.find('.jsEdit').on('click', this.doRequestToServer); - Что-то я такого метода даже не вижу.
7. userRating.attr('data-rating', param.userRating); - Для data атрибутов есть метод data().
8. Не надо использовать inline стили.
9. На js* классы стили не навешиваем, они чисто для логики.
10. А зачем нам вообще нужны штуки в духе:
   ```javascript
   .jsReviewData{
       background-color: rgba(33, 133, 208, 0.06);
   }
   ```
11. Стараемся не использовать кастомные стили, а если нужно, то их необходимо инкапсулировать внутри компонента. В противном случае, они могут повлиять на остальную страницу.

**Comment by jegius** [comment]
e88ab53a00f25b6ddd5b3fb035246c5495f97e9d

Саш готово! Все поправил, принимай)

af7640e5929d748ede6f56e498b4e45a7a313c19 сегодняшние правки

**Comment by ocassio** [comment]
1. JS файл назван с опечаткой.
2. this.content.find('.jsThisUserReview').find('.jsEdit') - Можно заменить на this.content.find('.jsThisUserReview .jsEdit').
3. userRatingReload.attr('data-rating', thisUserRating); - Для data аттрибутов есть метод data().
4. А почему на cancel нам нужно перезагружать страницу?
5. Вынеси case блоки в отдельные функции.
6. Данные для формы редактирования можно заполнять прямо на сервере.

**Comment by jegius** [comment]
3863b4e6391c25c3b810ecdd75ad4dd4a5b44884 Закончил правки)
76c4817b85d76e6813f774ad9674d0952e28d0ae

**Comment by ocassio** [comment]
1. Имена атрибутов и параметров в константы.
2. JSP из пропертей.
3. А почему так много методов имеет окончание *ByBase. Что это означает? :)
4. .jsReview p - Лучше сразу назначить класс этому элементу.
5. Забываем точки с запятой.
6. Inline стили убираем.

**Comment by jegius** [comment]
051ede86f245f57bcdcdf926fe2df72cdda7e296
Готово!
