### ISSUE TITLE
Компонент Shopping Cart

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#28]

**Comment by ocassio** [comment]
Насколько я понял, работы идут полным ходом, так что перевел в in progress.

**Comment by ocassio** [comment]
1. Зачем нам список Sales Order'ов? Как у нас может быть несколько заказов в одной корзине?
2. Редирект на страницу логина должен быть именно редиректом, а форвардом.
3. if (salesOrderList.isEmpty() || Objects.isNull(salesOrderList)) { - Второе условие недостижимо.
4. request.setAttribute("salesOrderListIsEmpty", "Empty"); - У тебя уже есть список, достаточно проверить его на пустоту. Зачем нам какие-то дополнительные параметры?
5. formActionOnShoppingCart - Нейминг :)
6. deletedProductInOrderItemDataBase - Удаленный продукт в базе данных пунктов заказа. И он там не один :)
7. Long.parseLong(String.valueOf(salesOrder.getLimit())) - Угадай, что произойдет, если будет введено число, которое входит в BigDecimal, но выходит за рамки long?
8. String.valueOf(request.getParameter("input")) - У тебя и так String.
9. var $this = this.content.find('.jsItemOrder'); - Зачем оно нам?
10. Переменные объявляй как можно ближе к месту использования. Во многих случаях можно вообще без них обойтись.
11. Много подобных фрагментов: 
    ```javascript
    var input = $(this).parent().find('.jsInput');
    var price = $(this).parent().parent().find('.jsPrice');
    ```
    А теперь представим такую ситуацию. Пришел верстальщик и поменял все блоки местами. Что будем делать?
12. Анонимные функции убираем. Переносим их в класс контроллера.
13. Таймер в поле контроллера.
14. globalUrl + '/cart' - Ты должен присылать сразу готовый URL. Тем более, что параметр у тебя называется shoppingCartUrl.
15. Зачем это нужно?
    ```javascript
    input.change();
    price.change();
    amount.change();
    ```
16. Расчеты, по хорошему, должны быть на сервере. Но если считаешь в данном кейсе оправданным, то ок.
17. priceMassive - Ну слово Array то ты должен знать :)
18. Зачем ты во всех обработчиках возвращаешь false? В твоем случае в этом не нужды.
19. Не надо использовать имена переменных с $. Лучше использовать говорящие названия.
20. Имена параметров и проч. - в константы.

**Comment by AndrewKozyrin** [comment]
1. Исправил
2. Исправил
3. Исправил
4. Исправил

**Comment by AndrewKozyrin** [comment]
5. Исправил
6. Исправил

**Comment by ocassio** [comment]
21. При изменении значения руками не происходит отправка AJAX запроса.
22. Серверная обработка ошибки числового формата выполнена некорректно.
23. Зачем мы перезагружаем страницу при нажатии на Enter?
24. Клиентская валидация вводимых значений. См. https://github.com/ncedu-tlt/ecomm/issues/38

**Comment by AndrewKozyrin** [comment]
Все исправил

**Comment by ocassio** [comment]
1. Таймаут не работает. Точнее он есть, но вся суть сводится к более поздней отсылке запроса.
2. По прежнему осталась возможность ввода отрицательных чисел.
3. Почему я не могу очистить поле Limit? После этого сервер упадет с ошибкой.
4. Сообщение о превышении лимита появляется только после перезагрузки страницы.
5. Пункт #20 до сих пор не выполнен.
6. Нейминг не исправлен.
7. <c:when test="${salesOrder.getOrderItems() != null}"> - Если все это условие не будет выполнено, то у тебя все развалится еще на предыдущей проверке.
8. `<a href='javascript:window.print(); void 0;'>` - Перенеси в JS контроллер.
9. .description - Где префикс js?
10. globalUrl - Глобальный URL. А куда?
11. var globalUrl = this.params.shoppingCartUrl; - Ты переменную используешь всего один раз. Стоит ли ее создавать?
12. Методы onMinusClick, onPlusClick и onInputWrite имеют практически идентичную логику. Перепиши так, чтобы не было дубляжа.
