### ISSUE TITLE
Компонент Company Info

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#29]
Отображает информацию о компании в футере.
Значения получаются из таблицы properties и будут конфигурироваться в админке.

**Comment by ilyad777** [comment]
Саш, в футере есть социальные сети, стоит ли добавить колонку social в таблицу properties типа boolean и по ней определять что пропертя соцсеть или по id social хранить строку с названием и урлой, затем получая ее разделять по какому-нибудь символу, если нет, то как сделать лучше?

**Comment by ocassio** [comment]
Давай проще, проперти facebookUrl, twitterUrl и прочие.

**Comment by ilyad777** [comment]
Т.е. только три соц сети, которые в мокапах и добавление других не требуется, только обновление ссылок. А если требуется, то где хранить id-шники по которым брать данные из проперти?

**Comment by ocassio** [comment]
Если понадобится завести новую, то администратор просто добавит новую проперти и изменит компонент.

**Comment by ilyad777** [comment]
Извратился как мог, готово d8d8ae6b9a594ea336244affd157a899fb6023e6
Админу не придется менять компонент ручками.

**Comment by ocassio** [comment]
Блин, запрос для социальных сетей это очень круто, конечно. Только вот не нужно. :)
Такой подход накладывает ограничения на именование остальных пропертей, что нам не нужно.
Если уж очень хочется иметь возможность добавлять новые соц. сети прямо из админки, то можно использовать специальный формат проперти.
Но так как такие вещи меняются очень редко, подход с простым получением каждого отдельного значения напрямую - вполне нормален.

**Comment by ilyad777** [comment]
Переделал 9bd25ad4b3d2a3075b5a38899ad41a7b20e99ae5

**Comment by ocassio** [comment]
getSocialsUrl - возвращает неопределенную мапу.

В остальном все норм, тикет закрываю.
