### ISSUE TITLE
Заверстать JSP

### ISSUE THREAD

**Issue by alzv0411** [ncedu-tlt/ecomm#3]
## [Страницы](https://github.com/ncedu-tlt/ecomm/tree/master/src/main/webapp/views/pages)

- [x] cart.jsp
- [x] category.jsp
- [x] index.jsp
- [x] login.jsp
- [x] ordersHistory.jsp
- [x] passwordRecovery.jsp
- [x] product.jsp
- [x] profile.jsp
- [x] registration.jsp
- [x] users.jsp

## [Фрагменты](https://github.com/ncedu-tlt/ecomm/tree/master/src/main/webapp/views/fragments)
- [x] head.jsp
- [x] topPanel.jsp

## [Компоненты](https://github.com/ncedu-tlt/ecomm/tree/master/src/main/webapp/views/components)
- [x] breadcrumbs.jsp
- [x] categories.jsp
- [x] companyInfo.jsp
- [x] dashboardMenu.jsp
- [x] filtering.jsp
- [x] login.jsp
- [x] ordersHistory.jsp
- [x] pagination.jsp
- [x] passwordRecovery.jsp
- [x] productDetails.jsp
- [x] productList.jsp
- [x] profile.jsp
- [x] profileIcon.jsp
- [x] registration.jsp
- [x] reviews.jsp
- [x] search.jsp
- [x] shoppingCart.jsp
- [x] shoppingCartIcon.jsp
- [x] userList.jsp

## Замечания
- [x] Общее - Мокап отражает расположение и функционал элементов. Дизайн на ваше усмотрение. Не стоит опускать Semantic до уровня моих художественных талантов.
- [x] Top Panel - Сделать крупнее. Как минимум текст.
- [x] Categories - Категории первого уровня также должны быть кликабельными.
- [x] Categories - Нужно унифицировать расположение категорий, чтобы их было удобно распечатывать в цикле.
- [x] Company Info - Разделители выполнить с помощью символа "|". Стили удалить. Тем более, что они не работают из-за опечатки.
- [x] Company Info - Прибить к низу страницы.
- [x] Cart - Беда с центрирование по вертикали (его нет).
- [x] Cart - Нет значений для Quantity.
- [x] Cart - Нет кнопки Apply для Limit.
- [x] Categories - Имена категорий должны быть кликабельными.
- [x] Categories - Имена товаров должны быть кликабельными.
- [x] Categories - Рейтинги не должны быть кликабельными.
- [x] Pagination - Привести к единому виду.
- [x] Filtering - Оформление. Аккордеон покрупнее. Значения выровнять по левому краю. Панель и кнопку сделать контрастной по отношению к странице.
- [x] Product Details - Цену покрупнее.
- [x] Product Details - Инициализировать рейтинги.
- [x] Product Details - Почему секции оформлены табами?
- [x] User List - Убрать содержимое компонентов Dashboard Menu и Pagination.
- [x] Search - Убрать link, inverted и circular классы с иконки. Слишком большой акцент.
- [x] Orders History - Total теряется на фоне цен товаров.
- [x] Orders History - Дата заказа теряется.
- [x] Dashboard Menu - Переделать табы с JS реализации на URL.

@jegius , @lordever, 
помечайте галочками те jsp, над которыми начинаете работать.

Верстка должна быть со статичными данными.

**Comment by ocassio** [comment]
Унификация категорий не принята. Как мы будем печатать их в цикле, если у нас явно прописано две колонки?

**Comment by jegius** [comment]
ad0a68db06429b7bdfa6caa872393bb17b24834f Поправил
