### ISSUE TITLE
Актуализировать скрипты БД

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#31]
Не только структуру, но и данные.

**Comment by ilyad777** [comment]
Готово 0d0df1b25f06df663e6a95cea2e9818632004e46

**Comment by ocassio** [comment]
Можешь еще изменения Андрея с ценами перенести?

**Comment by ilyad777** [comment]
Готово 7b4284441de2875c32d4cb5210fc450ee45cd0ed
