### ISSUE TITLE
Добавить возможность логирования при помощи Log4j

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#33]
Небольшой туториал: http://devcolibri.com/3413

**Comment by Garthdex** [comment]
https://github.com/ncedu-tlt/ecomm/commit/5e9b67e08ce2044718ff8208274f9d83bbcdf760
Я не смог найти какого-то панацейного решения. Нужно для каждого действия каждого сервлета сделать подобные действия, типа, LOG.info("что-то") или же все таки есть какое-то другое решение?

**Comment by ocassio** [comment]
Если тебе нужно логировать вообще все, то решение есть. Но оно нам и не нужно (да и вообще, трудно представить ситуацию, когда подобное может потребоваться). На данный момент нас интересуют только DAO методы.

По поводу настроек:
1. Не используй абсолютные пути.
2. Используй прямой слеш, а не обратный.
