### ISSUE TITLE
Некорректное отображение сообщений о пустой корзине

### ISSUE THREAD

**Issue by lordever** [ncedu-tlt/ecomm#35]
Если у пользователя есть товар в корзине, всё равно отображается сообщение о пустоте. Помимо этого, это сообщение дублируется

**Comment by AndrewKozyrin** [comment]
Сашь убери цикл и все будет нормально

**Comment by jegius** [comment]
1) был бесконечный цикл в addToShoppingCart в shopingCartService из за него в базе было около 30000 сейлс ордеров пустых, я его убрал.
2) У тебя некорректно выставлено уcловие, из-за него если сейлс ордер ранее не был создан периодичеcки создается два сейлс ордера  вместо одного.
