### ISSUE TITLE
Валидация в Input полях корзины

### ISSUE THREAD

**Issue by jegius** [ncedu-tlt/ecomm#38]
![image](https://cloud.githubusercontent.com/assets/11362702/24134520/56496b94-0e1e-11e7-9391-3d9f8c02406c.png)

Андрей сделай как будет возможность JS валидацию  в инпутах корзины.
https://semantic-ui.com/behaviors/form.html
У нас уже есть валидация на сервере LoginServlet и в JS loginServlet.js

если  данные все же уходят на сервлет то он ложится 
![image](https://cloud.githubusercontent.com/assets/11362702/24134629/f9aaeeb6-0e1e-11e7-81c6-a5d22c5188c3.png)
Нужно сделать чтобы он возвращал ошибку о недопустимых символах, как это сделанно в валидации формы входа.

Если сложности будут, спрашивай либо меня либо Антона, он уже делал валидацию форм

**Comment by ocassio** [comment]
Лучше сделать проверку на лету, чтобы пользователь просто не мог ввести ничего, кроме цифр.

**Comment by AndrewKozyrin** [comment]
исправил

**Comment by ocassio** [comment]
Закрываю тикет, так как он является частным случаем https://github.com/ncedu-tlt/ecomm/issues/28.
