### ISSUE TITLE
Компонент Product Comparator

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#39]
Компонент выполняет сравнение характеристик выбранных продуктов.
Для начала накидай простой мокап.

**Comment by Garthdex** [comment]
https://drive.google.com/drive/folders/0B1iKcScB1qMMYk8wbHZ6d2t0RW8
в мокапах, предпоследняя вкладка

**Comment by ocassio** [comment]
Группы характеристик забыл.

**Comment by Garthdex** [comment]
А, ну я это и имел ввиду) Исправил

**Comment by ocassio** [comment]
Ок, сойдет. Можешь начинать верстать.

**Comment by Garthdex** [comment]
сверстал(если это можно так назвать)

**Comment by ocassio** [comment]
1. Breadcrumbs тут не нужен.
2. Почему компонент назвал compare, хотя я явно написал, что это Product Comparator?
3. Кнопка Clear all немного не к месту выглядит.
4. Выровняй элементы внутри каждого продукта по центру.
5. Таблица какая-то поехавшая.

**Comment by Garthdex** [comment]
подправил(кнопку "Clear all" на 1 уровень с другими кнопками не удалось поставить)

**Comment by ocassio** [comment]
Ок. Добавь colspan для ячейки с именем группы характеристик и начинай писать логику.

Сразу упреждая вопросы:
1. Выбранные для сравнения товары храним в сессии.
2. Количество таких товаров ограничено. Например, тремя.

**Comment by jegius** [comment]
Готово)

**Comment by ocassio** [comment]
Сервлет можно упразднить, он ничего не делает.
