### ISSUE TITLE
Мокапы для админки

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#40]
Необходимо нарисовать примерный интерфейс админки, а затем произвести его разбивку на компоненты.

Какие пункты нам необходимы:
1. Управление метаданными (работа с категориями, группами характеристик и характеристиками)
2. Управление каталогом (продукты, значения характеристик и скидки)
3. Управление пользователями и заказами

Потом добавим еще, но пока начнем с этого.

**Comment by jegius** [comment]
https://drive.google.com/open?id=0B0IHRdBdIRKOS2RQcUV4S1lPNkE

Саш еще не доделал, но скажи сразу я в верном направлении иду?

**Comment by ocassio** [comment]
Проговорили оффлайн.

**Comment by lordever** [comment]
5 страниц:
 !1) Характеристики - содержат категории и характеристики по категориям, с возможностью удаления, добавления и редкатирования
 !2) Product list - страница с таблицей, в каждой строке с таблицей - продукты. 
 3) Создание и редактирование продукта
 4) Users - таблица с пользователями 
 5) Страница с возможностью удаления, блокирования, редактирования пользователя
 ?) Properties
 ?) SalesOrder

**Comment by jegius** [comment]
Мокапы Готовы!

**Comment by alzv0411** [comment]
@jegius , напиши ссылку на мокапы, пожалуйста

**Comment by jegius** [comment]
https://drive.google.com/drive/folders/0B1iKcScB1qMMYk8wbHZ6d2t0RW8

Готово!
