### ISSUE TITLE
Компонент Product List

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#8]
Отображает список товаров.

Возможно как отображение с разбивкой на категории, так и без них.

При клике на имя категории осуществляется переход на соответствующую страницу.
При клике на имя товара открывается страница с деталями.
При клике на кнопку Add to Cart происходит добавление товара в корзину.

В дальнейшем потребуется интеграция с компонентом Pagination.

**Comment by jegius** [comment]
Принял в работу

**Comment by jegius** [comment]
Не могу разобраться в гет запросах. Когда они у нас возникают, почемy при отсутствии запроса сервлет ложиться с NullPointExeption как этого избежать и как вывести категории на главную страницу при этом не модифицируя index.jsp

**Comment by jegius** [comment]
Готово 2c28d9db640535c5eb7f8856254add4c8c899f07
