### ISSUE TITLE
Компонент Breadcrumbs

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/ecomm#9]
Отображает иерархию категорий до текущей категории/товара.

При клике на пункт происходит переход на соответствующую страницу категории/товара.

**Comment by ilyad777** [comment]
Ближайшую неделю буду занят учебным процессом, пока не могу взяться за данную задачу.

**Comment by ilyad777** [comment]
Готово abc2b25afbaabf231bf790a3247e7c27802598d5

**Comment by ocassio** [comment]
Посмотри мокап для страницы продукта. Там несколько другое поведение.

**Comment by ilyad777** [comment]
окей, делал чисто относительно верстки, мокапы не смотрел, доделаю

**Comment by ilyad777** [comment]
Готово 10a8fbb787adf279e31962dc8f95cb7c0fa0b682
